using System;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.CompilerServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.237
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyCompanyAttribute("Monastry")]
[assembly: AssemblyVersionAttribute("0.0.0.0")]
[assembly: AssemblyFileVersionAttribute("0.0.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.0.0.1316fb765c7ad90f118a29459c058d01fac1ab32")]
[assembly: AssemblyTitleAttribute("Monastry.Continuations")]
[assembly: AssemblyProductAttribute("Monastry.Continuations")]
[assembly: AssemblyDescriptionAttribute("Monastry.Continuations is a product of Monastry - https://mzywitza@github.com/mzy" +
    "witza/Monastry.Continuations.git.")]
[assembly: AssemblyTrademarkAttribute("Monastry.Continuations - Monastry")]
[assembly: AssemblyCopyrightAttribute("Copyright ©  2011 Monastry, - Original author or authors")]

